### PR TITLE
Adding uniqueTypeName as an optional directiveArgument 

### PR DESCRIPTION
**Pull request by ahmoha**
uniqueTypeName behavior can be overridden by the user of the directive and passed as an argument. This way you can open it up for the one who is using it to customize the type name

### CODE REVIEW

**Comment by ahmoha** [comment]
> Thanks for the PR, can you add a test case for this please?

Added, thanks

**Comment by ahmoha** [comment]
@confuser if it's good to merge, can you create a new release tag for this?

**Comment by confuser** [comment]
Released as `v2.1.0`

**Comment by ahmoha** [comment]
Thanks! Appreciate your help here

**Pull request merged**
