### PR TITLE
adding support for the id scalar constrained as a string

### PR DESCRIPTION
**Pull request by mrcarolin**
this will allow custom format on the ID scalar.

`export declare const GraphQLString: GraphQLScalarType<string, string>;
export declare const GraphQLID: GraphQLScalarType<string, string>;`

### CODE REVIEW

**Comment by confuser** [comment]
Thanks @mrcarolin for this. Can you add some test cases?

**Comment by mrcarolin** [comment]
ok will do, ty

**Comment by mrcarolin** [comment]
@confuser updated with a couple tests showing how ID is treated just like string now

**Comment by kal4l** [comment]
@confuser Thank you for merging - if possible could a new release be created with this change?

**Pull request merged**
